function nf2ff_cleanup(basename);
  counter = 1;
  nf2ff_filename = basename;
  axis = {"x","y","z"};
  minmax = {"n","p"};
  fields = {"E","H"};
  for i = 1:numel(fields);
    for j = 1:numel(axis);
      for k = 1:numel(minmax);
        nf2ff_files{counter} = [nf2ff_filename, fields{i}, "_", axis{j}, minmax{k},".h5"];
        counter += 1;
  endfor;endfor;endfor;
  for idx = 1:numel(nf2ff_files);
    exist_ret = exist(nf2ff_files{idx}, "file");
    if exist_ret == 2;
      delete(nf2ff_files{idx});
    endif;
    if exist_ret == 0;
      fprintf(["Strange, file \"", nf2ff_files{idx}, "\" did not exist\n"]);
    endif;
  endfor;
endfunction;